function section(markdown = '', heading = '') {
  const text = String(markdown || '');
  const escaped = String(heading || '').replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const pattern = new RegExp(`^##\\s+${escaped}\\s*$`, 'im');
  const match = text.match(pattern);
  if (!match || typeof match.index !== 'number') return '';
  const start = match.index + match[0].length;
  const next = text.slice(start).search(/^##\s+/m);
  return (next >= 0 ? text.slice(start, start + next) : text.slice(start)).trim();
}

function lines(markdown = '', heading = '', limit = 8) {
  return section(markdown, heading)
    .split(/\r?\n/)
    .map((line) => line.replace(/^[-*]\s*/, '').replace(/^\[[ xX]\]\s*/, '').trim())
    .filter(Boolean)
    .slice(0, limit);
}

function bulletList(items = [], fallback = '- None') {
  if (!items.length) return fallback;
  return items.map((item) => `- ${item}`).join('\n');
}

function riskIcon(risk = '') {
  const value = String(risk || '').toLowerCase();
  if (value.includes('high')) return '🔴';
  if (value.includes('low')) return '🟢';
  return '🟡';
}

function safeToMergeText(result = '') {
  const value = section(result, 'Safe to merge?');
  return value || 'Not determined from the stored internal analysis.';
}

function relativeLink(path = '') {
  return String(path || '').replace(/^\/+/, '');
}

export function buildPrCommentDraft(item = {}) {
  const meta = item.pr_metadata || {};
  const result = String(item.result || '');
  const risk = item.risk_level || 'medium';
  const changedFiles = Array.isArray(item.changed_files) ? item.changed_files : [];
  const recommendedTests = Array.isArray(item.recommended_tests) && item.recommended_tests.length
    ? item.recommended_tests
    : lines(result, 'Recommended tests', 10);
  const mainRisks = lines(result, 'Main risks', 8);
  const summary = section(result, 'Summary') || 'Internal Codebase Brain analysis completed.';
  const safeToMerge = safeToMergeText(result);
  const contextFiles = Array.isArray(item.relevant_files) ? item.relevant_files : [];
  const repo = meta.repositoryFullName || 'repository';
  const prNumber = meta.prNumber ? `#${meta.prNumber}` : 'PR';

  return `## Codebase Brain internal review draft

${riskIcon(risk)} **Risk level:** ${String(risk).toUpperCase()}

**PR:** ${repo}${meta.prNumber ? `#${meta.prNumber}` : ''}
${meta.title ? `**Title:** ${meta.title}\n` : ''}
### Summary

${summary}

### Main risks

${bulletList(mainRisks)}

### Recommended tests

${bulletList(recommendedTests)}

### Changed files

${bulletList(changedFiles.map(relativeLink).slice(0, 20))}

### Context files reviewed

${bulletList(contextFiles.map(relativeLink).slice(0, 20))}

### Safe to merge?

${safeToMerge}

---
Generated by Codebase Brain from an internal analysis of ${repo} ${prNumber}. No tests were run and no GitHub write action was performed by Codebase Brain.`;
}

export function hasPrCommentDraft(item = {}) {
  return Boolean(item?.result && item?.pr_metadata);
}
